name: Generador Dinámico IPTV

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

# [CORRECCIÓN ERROR 128] Otorgamos privilegios de escritura al bot
permissions:
  contents: write

jobs:
  compilar_lista:
    runs-on: ubuntu-latest
    
    steps:
      # [CORRECCIÓN WARNING] Actualizado a v4
      - name: 1. Clonar el repositorio
        uses: actions/checkout@v4

      # [CORRECCIÓN WARNING] Actualizado a v5
      - name: 2. Configurar entorno Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 3. Ejecutar motor ETL
        run: python generador.py

      - name: 4. Guardar los resultados en el repositorio
        run: |
          git config --global user.name 'Bot Automatizado'
          git config --global user.email 'bot@tuservidor.com'
          git add mi_lista_personalizada.m3u
          git commit -m "Actualización automática de nodos de red" || exit 0
          git push
